### ISSUE TITLE
Outputs Garbage to Screen On Windows

### ISSUE THREAD

**Issue by wcrisman** [apostrophecms/cli#17]
When I run apos create XXX all I am getting is infinitely scrolling garbage to my terminal.  

Give that my dev machine is not exactly clean, I took a clean windows 10 laptop and installed the latest NodeJS (MSI from their site with default installer options).  I updated NPM (via their instructions).  I installed @apostrophecms/cli as per your instructions, and ran `apos create XXX`.

**Comment by wcrisman** [comment]
![Screenshot 2022-01-08 145759](https://user-images.githubusercontent.com/24438893/148662718-a3b07a63-eba5-4f28-b37c-4aa757413cc7.jpg)

**Comment by boutell** [comment]
Hi @wcrisman, I think this may be related to an issue I just fixed. Would you please give this another try?

(I'm not sure that you did follow our procedure, as if you used `npm install -g @apostrophecms/cli` I don't really see how you could get the behavior you did. However if you git cloned the cli repo and ran `npm update`, you could get that behavior, due to a third-party module that went a big rogue this week. Also, you're the second person to report this. So we have pinned that dependency and made a new release just to make absolutely sure.)

But if you still get the behavior there's a possibility it is just a Windows-specific incompatibility. Apostrophe, like all Node.js apps, runs best on Unix and the best way to run it on Windows is via the Linux Subsystem for WIndows (according to MIcrosoft's own documentation), but if there is a platform incompatibility with running Apostrophe without the Linux subsystem that you'd like to help address we would welcome a PR.

**Comment by wcrisman** [comment]
Fixed.  Thank you!
